import {
  SiTypescript,
  SiPhp,
  SiPython,
  SiGo,
  SiHtml5,
  SiCss,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiFlask,
  SiJquery,
  SiPrisma,
  SiTailwindcss,
  SiBootstrap,
  SiMysql,
  SiPostgresql,
  SiMongodb,
  SiGit,
  SiDocker,
  SiPostman,
  SiJira,
  SiSlack,
  SiVercel,
  SiCloudflare,
  SiStripe,
  FaCloud,
  FaAws,
  FaAmazon,
} from "./icons";

export const allLogos = [
  {
    node: <SiTypescript />,
    title: "TypeScript",
    href: "https://typescriptlang.org",
  },
  { node: <SiPhp />, title: "PHP", href: "https://php.net" },
  { node: <SiPython />, title: "Python", href: "https://python.org" },
  { node: <SiGo />, title: "Go", href: "https://go.dev" },
  {
    node: <SiHtml5 />,
    title: "HTML",
    href: "https://developer.mozilla.org/en-US/docs/Web/HTML",
  },
  {
    node: <SiCss />,
    title: "CSS",
    href: "https://developer.mozilla.org/en-US/docs/Web/CSS",
  },
  { node: <SiReact />, title: "React", href: "https://react.dev" },
  { node: <SiNextdotjs />, title: "Next.js", href: "https://nextjs.org" },
  { node: <SiNodedotjs />, title: "Node.js", href: "https://nodejs.org" },
  { node: <SiExpress />, title: "Express.js", href: "https://expressjs.com" },
  {
    node: <SiFlask />,
    title: "Flask",
    href: "https://flask.palletsprojects.com",
  },
  { node: <SiJquery />, title: "jQuery", href: "https://jquery.com" },
  { node: <SiPrisma />, title: "Prisma", href: "https://prisma.io" },
  {
    node: <SiTailwindcss />,
    title: "Tailwind",
    href: "https://tailwindcss.com",
  },
  {
    node: <SiBootstrap />,
    title: "Bootstrap",
    href: "https://getbootstrap.com",
  },
  { node: <SiMysql />, title: "MySQL", href: "https://mysql.com" },
  {
    node: <SiPostgresql />,
    title: "PostgreSQL",
    href: "https://postgresql.org",
  },
  { node: <SiMongodb />, title: "MongoDB", href: "https://mongodb.com" },
  {
    node: <FaAws />,
    title: "DynamoDB",
    href: "https://aws.amazon.com/dynamodb",
  },
  { node: <SiGit />, title: "Git", href: "https://git-scm.com" },
  { node: <SiDocker />, title: "Docker", href: "https://docker.com" },
  { node: <FaAmazon />, title: "AWS", href: "https://aws.amazon.com" },
  { node: <SiPostman />, title: "Postman", href: "https://postman.com" },
  {
    node: <SiJira />,
    title: "Jira",
    href: "https://atlassian.com/software/jira",
  },
  { node: <SiSlack />, title: "Slack", href: "https://slack.com" },
  { node: <SiVercel />, title: "Vercel", href: "https://vercel.com" },
  {
    node: <SiCloudflare />,
    title: "Cloudflare",
    href: "https://cloudflare.com",
  },
  { node: <SiStripe />, title: "Stripe", href: "https://stripe.com" },
  { node: <FaCloud />, title: "Ollama", href: "https://ollama.com" },
];
